name: Generate Clean Markdown Pages

on:
  push:
    branches: [ master ]

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed Markdown files
        id: changed_files
        run: |
          FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --diff-filter=d | grep '\.md$' | grep -v '#' )
          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "changed markdown files:"
          echo "$FILES"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4

      - name: Process Markdown files
        if: steps.changed_files.outputs.files != ''
        run: |
          mkdir -p output

          for file in ${{ steps.changed_files.outputs.files }}; do
            echo "Processing $file ..."
            GITHUB_URL="https://github.com/${{ github.repository }}/blob/main/$file"
            OUTPUT_PATH="output/${file%.md}.html"
            mkdir -p $(dirname $OUTPUT_PATH)

            # 带重试机制的调用 (最多3次尝试)
            max_retries=2
            attempt=0
            until python .github/scripts/clean-page.py "$GITHUB_URL" "$OUTPUT_PATH"; do
              attempt=$((attempt + 1))
              if [ $attempt -gt $max_retries ]; then
                echo "Failed after $max_retries attempts"
                exit 1
              fi
              echo "Retrying ($attempt/$max_retries)..."
              sleep 5
            done
          done

      - name: Deploy to gh-pages
        if: steps.changed_files.outputs.files != ''
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true
